platform: linux

image_resource:
  type: registry-image
  source: {repository: bosh/main}

inputs:
- name: bosh-linux-stemcell-builder
- name: bosh-stemcells-ci
- name: bosh-cli
- name: stemcell
- name: syslog-release
- name: os-conf-release
- name: director-state

params:
  BOSH_os_name: required
  package: .

run:
  path: bosh-stemcells-ci/pipelines/ubuntu-xenial/170.x/tasks/test-stemcell.sh
